Initial commit to create the barebones stats component and stats being
uclaacm/conditional-learning-lab pull request #26
Opened 2021-11-16 10:07 UTC by ldalton02

passed down from landing page.

Adds some css into stats.css to style the bar.

Uses Math.random to generate random numbers from 1 to 10 for initial
stats.

2021-11-16 10:08 UTC, ldalton02 commented
closes #22

2021-11-18 20:32 UTC, ldalton02 commented
Let me know what you think, I can always add more changes/change font if it doesn't look close enough to figma

2021-11-19 01:22 UTC, nendow02 approved these changes
lgtm, I’m going to request @reginawang3495 to quickly look over this and @archishadatta too just because there’s some css in here. Nice job Luke!

2021-11-24 00:43 UTC, archishadatta requested changes

2021-11-24 00:43 UTC, archishadatta commented on src/styles/stats.scss
> +  color: #ffab00;
Use scss variables for the colors

2021-11-24 00:43 UTC, archishadatta commented on src/styles/stats.scss
>    height: 50px;
```suggestion
  height: 50px;
  padding: 1em;
```

2021-11-25 12:52 UTC, reginawang3495 requested changes
oops!! I forgot to submit the review :)

2021-11-30 04:49 UTC, ldalton02 commented
My bad on late response time. I changed Stats.tsx to create an object out of the props and then map the object to display all of the stats. Also moved the random number generating function to common/math.js in the src folder

2021-11-30 05:01 UTC, reginawang3495 requested changes
I dmed some things to consider changing as well!!

2021-12-06 01:22 UTC, reginawang3495 reviewed
Quick glance — shape of PR looks really great to me!!

2022-01-05 05:11 UTC, archishadatta approved these changes

2022-01-05 07:31 UTC, reginawang3495 requested changes
A couple small ideas to improve + would recommend running “yarn lint-fix”

2022-01-05 07:31 UTC, reginawang3495 commented on src/components/shared/Stats.tsx
> +type statsObject = {
I would make a playerStats object somewhere and use it both here and in the state of App.tsx

2022-01-05 07:31 UTC, reginawang3495 commented on src/components/shared/Stats.tsx
> +  const renderStats = () => {
Since there isn’t much code and this is only used once, I’d prefer to in-line this

2022-01-06 01:48 UTC, reginawang3495 approved these changes
looks great!! a few tiny changes, then feel free to merge :)

some small formatting issues (like extra lines, and not having a new line at the end of a file), but not a big deal. Feel free to ask why as always!

2022-01-08 00:57 UTC, ldalton02 commented on src/common/types.ts
> +}
It might not always be the same in the future but good to manually define it to prevent issues

2022-01-08 01:01 UTC, merged